resolver: nightly-2016-05-21

packages:
- '.'

- location:
    git: https://github.com/christetreault/liquiddesugar.git
    commit: 792501fdbf75edbdeb496f9e16ee7ddf6fd2decf

- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint.git
    commit: d6c56f1a75fd546685498231f7ca273ffef36a2c

- location:
    git: https://github.com/ucsd-progsys/liquidhaskell.git
    commit: b11d400d299c0ee0a507f0c776b6459820fd0b96

extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.0
- cpphs-1.16

