resolver: nightly-2016-05-21

packages:
- '.'

- location:
    git: https://github.com/christetreault/liquiddesugar.git
    commit: 792501fdbf75edbdeb496f9e16ee7ddf6fd2decf

- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint.git
    commit: 0e021dcc32c9a104d691930f2ce911858ff7fbfc

- location:
    git: https://github.com/ucsd-progsys/liquidhaskell.git
    commit: 9bf9ab4654f618634aeb932b98396da048935a06

extra-deps:
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.0
- cpphs-1.16

